In [1]:
import pandas as pd
import numpy as np

In [2]:
races = pd.read_csv("../data/races.csv")
results = pd.read_csv("../data/results.csv")
drivers = pd.read_csv("../data/drivers.csv")

In [3]:
results = results[
    ["raceId",
     "driverId",
     "constructorId",
     "grid",
     "positionOrder",
     "points"]
]

results.head()

   raceId  driverId  constructorId  grid  positionOrder  points
0      18         1              1     1              1    10.0
1      18         2              2     5              2     8.0
2      18         3              3     7              3     6.0
3      18         4              4    11              4     5.0
4      18         5              1     3              5     4.0

In [4]:
results["winner"] = np.where(
    results["positionOrder"] == 1,
    1,
    0
)

results.head()

   raceId  driverId  constructorId  grid  positionOrder  points  winner
0      18         1              1     1              1    10.0       1
1      18         2              2     5              2     8.0       0
2      18         3              3     7              3     6.0       0
3      18         4              4    11              4     5.0       0
4      18         5              1     3              5     4.0       0

In [5]:
results["winner"].value_counts()

winner
0    25631
1     1128
Name: count, dtype: int64

In [6]:
driver_stats = (
    results.groupby("driverId")["points"]
    .mean()
    .reset_index()
)

driver_stats.columns = [
    "driverId",
    "avg_driver_points"
]

driver_stats.head()

   driverId  avg_driver_points
0         1          13.540730
1         2           1.407609
2         3           7.740291
3         4           5.764851
4         5           0.937500

In [7]:
ml_data = results.merge(
    driver_stats,
    on="driverId",
    how="left"
)

ml_data.head()

,raceId,driverId,constructorId,grid,positionOrder,points,winner,avg_driver_points
0,18,1,1,1,1,10.0,1,13.540730
1,18,2,2,5,2,8.0,0,1.407609
2,18,3,3,7,3,6.0,0,7.740291
3,18,4,4,11,4,5.0,0,5.764851
4,18,5,1,3,5,4.0,0,0.937500

In [8]:
print(ml_data.shape)

(26759, 8)

# Conclusion

Feature engineering was performed on race results data.

A binary target variable (winner) was created and average driver points were calculated.

The resulting dataset is now suitable for machine learning preparation.