In [1]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [2]:
results = pd.read_csv("../data/results.csv")

In [3]:
results = results[
    [
        "raceId",
        "driverId",
        "grid",
        "points",
        "positionOrder"
    ]
]

results["winner"] = np.where(
    results["positionOrder"] == 1,
    1,
    0
)

results.head()

   raceId  driverId  grid  points  positionOrder  winner
0      18         1     1    10.0              1       1
1      18         2     5     8.0              2       0
2      18         3     7     6.0              3       0
3      18         4    11     5.0              4       0
4      18         5     3     4.0              5       0

In [4]:
driver_stats = (
    results.groupby("driverId")["points"]
    .mean()
    .reset_index()
)

driver_stats.columns = [
    "driverId",
    "avg_driver_points"
]

driver_stats.head()

   driverId  avg_driver_points
0         1          13.540730
1         2           1.407609
2         3           7.740291
3         4           5.764851
4         5           0.937500

In [5]:
ml_data = results.merge(
    driver_stats,
    on="driverId",
    how="left"
)

ml_data.head()

   raceId  driverId  grid  points  positionOrder  winner  avg_driver_points
0      18         1     1    10.0              1       1          13.540730
1      18         2     5     8.0              2       0           1.407609
2      18         3     7     6.0              3       0           7.740291
3      18         4    11     5.0              4       0           5.764851
4      18         5     3     4.0              5       0           0.937500

In [6]:
X_old = ml_data[
    [
        "grid",
        "points"
    ]
]

y = ml_data["winner"]

In [7]:
X_train, X_test, y_train, y_test = train_test_split(
    X_old,
    y,
    test_size=0.2,
    random_state=42
)

old_model = LogisticRegression()

old_model.fit(
    X_train,
    y_train
)

old_predictions = old_model.predict(X_test)

old_accuracy = accuracy_score(
    y_test,
    old_predictions
)

print("Old Model Accuracy:", old_accuracy)

Old Model Accuracy: 0.9538490284005979

In [8]:
X_new = ml_data[
    [
        "grid",
        "points",
        "avg_driver_points"
    ]
]

In [9]:
X_train, X_test, y_train, y_test = train_test_split(
    X_new,
    y,
    test_size=0.2,
    random_state=42
)

new_model = LogisticRegression()

new_model.fit(
    X_train,
    y_train
)

new_predictions = new_model.predict(X_test)

new_accuracy = accuracy_score(
    y_test,
    new_predictions
)

print("New Model Accuracy:", new_accuracy)

New Model Accuracy: 0.9605754857997011

In [10]:
print("Old Model Accuracy :", old_accuracy)
print("New Model Accuracy :", new_accuracy)

Old Model Accuracy : 0.9538490284005979
New Model Accuracy : 0.9605754857997011

# Conclusion

A new feature called avg_driver_points was created and added to the model.

Two Logistic Regression models were compared:

1. Using grid and points
2. Using grid, points, and avg_driver_points

This notebook demonstrates how feature engineering can improve machine learning models by providing additional information to the algorithm.